### ISSUE TITLE
Compare to iso3166-country-codes

### ISSUE THREAD

**Issue by 3noch** [andrewthad/country#1]
How does this project compare to https://hackage.haskell.org/package/iso3166-country-codes?

**Comment by andrewthad** [comment]
The main things are:

- it doesn't use an ADT to represent countries, using its three-digit country code instead.
- it doesn't use `String` for encoding/decoding
- there are plans to provide more stuff, like two-alpha and three-alpha country codes.
- there are also plans to add a `Primitive` and allow it to be used in unboxed vectors.

I'll try to add this to a readme after I flush out the features more.

**Comment by 3noch** [comment]
Excellent! Would it, perchance, also have a more liberal license?

**Comment by 3noch** [comment]
I may very well switch my library to use this instead.

**Comment by andrewthad** [comment]
I think I've got this as BSD 3 right now. I can do MIT instead if that's better for some reason. I cannot ever remember what the actual differences between these two are in practice.

**Comment by 3noch** [comment]
Me neither BSD3 is fine since most of Hackage is BSD3.

**Comment by 3noch** [comment]
`iso3166-country-codes` is LGPL so that's another [good] reason to use this package instead. I've spoken to the author of `iso3166-country-codes` about that and he's aware of the issue. I don't think he's actively working on the project though and may be willing to deprecate his in favor of something else.

**Comment by andrewthad** [comment]
I just published this to hackage. Let me know if there are features you would like that you do not see.

**Comment by andrewthad** [comment]
[Hackage link](http://hackage.haskell.org/package/country)

**Comment by chessai** [comment]
We can probably add the differences to the README or something, but i think this issue can be closed since the question was answered
