### ISSUE TITLE
Adding comments for some countries in Country.Identifier

### ISSUE THREAD

**Issue by MaxGabriel** [andrewthad/country#13]
Hi, yesterday I had a bug where I used `congo` from `Country.Identifier` rather than `congoDemocraticRepublicOfThe`. I assumed these were aliases, since people call The Democratic Republic of Congo "Congo" sometimes, but actually `congo` is the Republic of Congo.

Would you be open to a PR that distinguishes the two in `Country.Identifier` with a comment? Looking at the code, it looks like if you're open to this, the best way to do it would be to add a `comment` column to the CSV, and pull the comment out of that if present.

I haven't considered all the countries, but some other countries that might benefit from comments could be North/South Korea (`koreaDemocraticPeoplesRepublicOf`/`koreaRepublicOf`), `laoPeoplesDemocraticRepublic` (Laos), `holySee` (Rome, The Vatican, Vatican City).

Another way this might be implemented is to pull in the data from `aliases.txt` to generate comments for each country. Something like:

```
-- | Suriname, Dutch Guiana, Netherlands Guiana, Republic of Suriname, Republiek Suriname, Surinam
suriname :: Country
```

This would be more verbose (e.g. Russia has 23 aliases), but might be helpful for people who don't use the English/American names I'm familiar with.

Thoughts?

**Comment by chessai** [comment]
Yes, I would be open to that. I think your second idea about generating comments from aliases.txt would be most helpful to end users, effectively stating which aliases matter for the given country. I'm not worried about verbosity because people use grep to find countries anyway.

**Comment by andrewthad** [comment]
I’m cool with both of those ideas. Adding the column to the CSV for comments and using the aliases file for additional identifiers would both be welcome additions.
