### ISSUE TITLE
Consider using digits as well as, or instead of, Word16

### ISSUE THREAD

**Issue by tonymorris** [andrewthad/country#3]
There are guarantees that the `Word16` is less than `1000`. This can be represented in the type system as three digits.

https://hackage.haskell.org/package/digit

Once that is safely represented, then functions to/from `Word16` and other number types can be implemented.

**Comment by andrewthad** [comment]
I'm not keen on this. The digit-based representation is slower and less space-efficient than the `Word16`-based one. Since I'm just maintaining the invariants internally, and end-users never have to worry about this, I prefer to use `Word16`.

**Comment by chessai** [comment]
I don't think this is going to happen. If a new argument is presented for using the `digit` library, please feel free to re-open.
