### ISSUE TITLE
Use parsers instead of attoparsec

### ISSUE THREAD

**Issue by tonymorris** [andrewthad/country#4]
Instead of the `attoparsec` library, consider using the `parsers` library which generalises it, and leaves the implementation as a decision for the end user. The `attoparsec` library is an instance of the type-classes within `parsers`.

https://hackage.haskell.org/package/parsers

**Comment by andrewthad** [comment]
The `parsers` library only seems to work with `attoparsec` and `parsec`. What's more, `parsec` is no longer maintained and has been superseded by `megaparsec`. So, I'm not keen on this. I would take a PR that simply added a `parsec` parser. We could rename `parser` and then have:

    attoparser :: AT.Parser Country
    parser :: PT.Parser Country -- from parsec

I just looked at megaparsec and saw that it has `QuickCheck` as a dep, so I won't take anything that causes `country` to incur a dependency on `megaparsec`.

**Comment by chessai** [comment]
I don't think this is going to happen.
