### ISSUE TITLE
Consider a Prism' instead of encode/decode

### ISSUE THREAD

**Issue by tonymorris** [andrewthad/country#5]
The functions `encodeEnglish` and `decode` form a `Prism'`

https://hackage.haskell.org/package/lens-4.15.1/docs/src/Control.Lens.Prism.html#prism%27

**Comment by chessai** [comment]
this would force us to depend on lens. i don't think we are going to do this.

**Comment by andrewthad** [comment]
This doesn't force a dependency on lens since Prism is a type synonym:

    type Prism s t a b = forall p f. (Choice p, Applicative f) => p a (f b) -> p s (f t)
    type Prism' s a = Prism s s a a

However, I've never needed something like this. It could be useful with `lens-aeson` though, so if anyone wants to implement this, go for it.

**Comment by chessai** [comment]
it is a synonym, but the `Choice` typeclass is implemented in the `lens` library

**Comment by chessai** [comment]
this is why `microlens` does not implement `Prism`, because its dependency footprint is supposed to be just base/transformers

**Comment by andrewthad** [comment]
Dang. Yeah, this seems unlikely to happen then.
