### ISSUE TITLE
Use two character data type instead of Text

### ISSUE THREAD

**Issue by tonymorris** [andrewthad/country#6]
Functions such as `alphaTwoUpper` and `alphaThreeUpper` use a `Text` which guarantees length=2. Consider instead using a data type: `data TwoChars = TwoChars Char Char` from which there is a function to/from a `Text`. That pair of functions will form a `Prism'`. This safety helps library use.

**Comment by andrewthad** [comment]
I'm alright with adding a `TwoChars` and `ThreeChars` data type. As long as it adds new functions and doesn't get rid of existing ones, it would be fine. You'd probably want to stick these types (and their text conversion functions) in a `Data.Char.Multiple` module or something like that. Although, I will say that the value of having a fixed-length text type is questionable to me. But if there's something you need it for, by all means, implement it and I'll take a PR.

**Comment by chessai** [comment]
Going to close this, if anyone becomes interested in doing this feel free to re-open
